import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, ArrowRight, Star, Code, Map, Sparkles, X, Loader2 } from "lucide-react";
import { GlobalLoader } from "@/components/ui/GlobalLoader";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/services/api";
import { motion, useScroll, useSpring, AnimatePresence } from "framer-motion";
import { useRef, useState } from "react";

export const Route = createFileRoute("/_authenticated/roadmap")({
  component: RoadmapPage,
});

interface Milestone {
  step: string;
  title: string;
  description: string;
  status: "completed" | "in-progress" | "pending";
  targetSkill?: string;
  date: string;
}

interface RoadmapResponse {
  success: boolean;
  data: {
    milestones: Milestone[];
  };
}

function RoadmapPage() {
  const containerRef = useRef<HTMLDivElement>(null);
  const queryClient = useQueryClient();
  const [selectedMilestone, setSelectedMilestone] = useState<Milestone | null>(null);
  const [isVerifying, setIsVerifying] = useState(false);
  const [verifyError, setVerifyError] = useState("");
  const [needsGithubLink, setNeedsGithubLink] = useState(false);
  const [expandedResources, setExpandedResources] = useState(false);

  const { data, isLoading, error } = useQuery({
    queryKey: ["roadmap"],
    queryFn: async () => {
      try {
        const res = await api.get<RoadmapResponse>("/api/roadmap/generate");
        return res.data;
      } catch (err: any) {
        if (err.response?.status === 403) {
          setNeedsGithubLink(true);
        }
        throw err;
      }
    },
    refetchOnWindowFocus: false,
    retry: false, // Don't keep retrying if they haven't uploaded a resume
  });

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start center", "end center"]
  });

  const scaleY = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  const milestones = data?.data?.milestones || [];

  return (
    <div className="p-6 lg:p-12 space-y-12 font-sans max-w-screen-2xl mx-auto pb-32 relative overflow-x-hidden">
      {/* Background glow */}
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-full h-[800px] rounded-full opacity-[0.04] pointer-events-none"
        style={{ background: "radial-gradient(circle, var(--accent-violet) 0%, transparent 70%)", filter: "blur(120px)" }} />

      {/* Header */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: "easeOut" }}
        className="border-b border-slate-200 dark:border-white/5 pb-8 relative z-10 text-center md:text-left flex flex-col md:flex-row items-center md:items-end justify-between gap-6 group"
      >
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 text-xs font-bold uppercase tracking-widest shadow-[0_0_20px_rgba(139,92,246,0.15)] group-hover:shadow-[0_0_25px_rgba(139,92,246,0.3)] transition-all">
            <Sparkles className="w-4 h-4 animate-pulse" />
            <span>AI-Powered Career Navigation</span>
          </div>
          
          <motion.h2 
            whileHover={{ scale: 1.02 }}
            className="text-4xl md:text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-fuchsia-400 to-cyan-400 font-display tracking-tight drop-shadow-sm cursor-default flex flex-wrap items-center justify-center md:justify-start gap-3"
          >
            <Map className="w-10 h-10 md:w-14 md:h-14 text-violet-400 drop-shadow-[0_0_15px_rgba(139,92,246,0.5)] group-hover:rotate-12 transition-transform duration-500" />
            Real Career Roadmap
          </motion.h2>
          
          <p className="text-base md:text-lg text-slate-400 dark:text-white/60 mt-2 font-medium max-w-2xl leading-relaxed group-hover:text-slate-300 dark:group-hover:text-white/80 transition-colors">
            Personalized, actionable milestones generated by AI based on your unique profile gaps and ultimate career goals.
          </p>
        </div>
      </motion.div>

      {/* Loading State */}
      {isLoading && (
        <GlobalLoader singleText="Generating Career Roadmap..." />
      )}

      {/* Error / No Profile State */}
      {error && !isLoading && (
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="glass-card p-12 text-center flex flex-col items-center max-w-2xl mx-auto border-rose-500/20 bg-rose-500/5 shadow-[0_0_40px_rgba(244,63,94,0.1)]"
        >
          <div className="w-16 h-16 rounded-full bg-rose-500/10 flex items-center justify-center mb-4">
            <Star className="w-8 h-8 text-rose-400" />
          </div>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">No Profile Detected</h3>
          <p className="text-sm text-slate-500 dark:text-white/60">
            We need your resume to generate a personalized career roadmap. Please upload your resume on the dashboard first!
          </p>
        </motion.div>
      )}

      {/* Timeline Milestones */}
      {!isLoading && !error && milestones.length > 0 && (
        <div ref={containerRef} className="max-w-5xl mx-auto relative z-10 pt-10 pb-20">
          
          {/* Animated Timeline Vertical Line Background */}
          <div className="absolute left-8 md:left-1/2 -translate-x-1/2 top-0 bottom-0 w-[2px] bg-slate-200 dark:bg-white/5 rounded-full overflow-hidden">
            <motion.div
              animate={{ top: ["-10%", "110%"] }}
              transition={{ repeat: Infinity, duration: 4, ease: "linear" }}
              className="absolute left-0 w-full h-64 bg-gradient-to-b from-transparent via-blue-500 to-transparent opacity-80"
            />
          </div>
          
          {/* Active Scroll Progress Line */}
          <motion.div 
            style={{ scaleY, transformOrigin: 'top' }}
            className="absolute left-8 md:left-1/2 -translate-x-1/2 top-0 bottom-0 w-[4px] bg-gradient-to-b from-blue-400 via-violet-500 to-emerald-400 rounded-full shadow-[0_0_20px_rgba(139,92,246,0.6)] z-0"
          />

          {/* Timeline Start Point */}
          <div className="absolute left-8 md:left-1/2 -translate-x-1/2 top-0 w-5 h-5 rounded-full bg-white dark:bg-[#0d1527] border-4 border-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.8)] z-10 flex items-center justify-center" />
          
          {/* Timeline End Point (Target) */}
          <div className="absolute left-8 md:left-1/2 -translate-x-1/2 bottom-0 w-6 h-6 rounded-full bg-white dark:bg-[#0d1527] border-4 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.8)] z-10 flex items-center justify-center">
            <div className="w-2 h-2 rounded-full bg-emerald-400" />
          </div>

          <div className="space-y-12 md:space-y-24 mt-12 mb-12">
            {milestones.map((milestone, idx) => {
              const isCompleted = milestone.status === "completed";
              const isInProgress = milestone.status === "in-progress";
              const isEven = idx % 2 === 0;

              return (
                <div key={milestone.step} className={`relative flex flex-col md:flex-row justify-between items-center w-full group ${isEven ? 'md:flex-row-reverse' : ''}`}>
                  
                  {/* The Card - takes 45% width on desktop */}
                  <motion.div
                    initial={{ opacity: 0, y: 50, filter: "blur(8px)" }}
                    whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.7, delay: 0.1, type: "spring", bounce: 0.4 }}
                    className={`w-full pl-24 pr-4 md:px-0 md:w-[45%] flex ${isEven ? 'md:justify-start' : 'md:justify-end'}`}
                  >
                    <motion.div
                      whileHover={{ scale: 1.03, y: -5 }}
                      whileTap={{ scale: 0.98 }}
                      className={`glass-card p-6 md:p-8 relative overflow-hidden transition-all duration-500 cursor-default w-full shadow-lg ${
                        isInProgress 
                          ? "border-blue-500/40 shadow-[0_0_30px_rgba(59,130,246,0.15)] group-hover:border-blue-400/70 group-hover:shadow-[0_0_50px_rgba(59,130,246,0.3)]" 
                          : isCompleted
                          ? "group-hover:border-emerald-500/30 group-hover:shadow-[0_0_40px_rgba(16,185,129,0.15)]"
                          : "group-hover:border-violet-500/30 group-hover:shadow-[0_0_40px_rgba(139,92,246,0.15)]"
                      }`}
                    >
                      {/* Subtle hover gradient background */}
                      <div className={`absolute inset-0 bg-gradient-to-br opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none ${
                        isInProgress ? "from-blue-500/5 to-violet-500/5" : isCompleted ? "from-emerald-500/5 to-transparent" : "from-violet-500/5 to-transparent"
                      }`} />

                      {isInProgress && (
                        <motion.div 
                          layoutId="active-indicator"
                          className="absolute top-0 left-0 w-full h-[3px] bg-gradient-to-r from-blue-400 via-violet-500 to-blue-400 bg-[length:200%_auto] animate-gradient shadow-[0_0_15px_rgba(59,130,246,0.8)]" 
                        />
                      )}

                      {/* Description Content */}
                      <div className={`space-y-4 relative z-10 ${isEven ? 'md:text-left' : 'md:text-right'}`}>
                        <div className={`flex flex-col sm:flex-row justify-between gap-3 ${isEven ? 'sm:items-center' : 'sm:flex-row-reverse sm:items-center'}`}>
                          <h3 className={`text-lg font-bold text-slate-900 dark:text-white font-display flex items-center gap-2 transition-colors duration-300 ${
                            isInProgress ? "group-hover:text-blue-600 dark:group-hover:text-blue-300" : isCompleted ? "group-hover:text-emerald-600 dark:group-hover:text-emerald-300" : "group-hover:text-violet-600 dark:group-hover:text-violet-300"
                          }`}>
                            {milestone.title}
                            {isInProgress && (
                              <span className="flex h-2.5 w-2.5 relative ml-1">
                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                                <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-blue-500 shadow-[0_0_10px_rgba(59,130,246,0.8)]"></span>
                              </span>
                            )}
                          </h3>
                          <span className={`text-[10px] font-bold px-3 py-1 rounded-full w-fit tracking-wider uppercase transition-colors duration-300 ${
                            isCompleted 
                              ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 group-hover:bg-emerald-500/20 group-hover:shadow-[0_0_15px_rgba(16,185,129,0.2)]" 
                              : isInProgress 
                              ? "bg-blue-500/10 text-blue-400 border border-blue-500/20 shadow-[0_0_10px_rgba(59,130,246,0.1)] group-hover:bg-blue-500/20" 
                              : "bg-slate-100 dark:bg-white/5 text-slate-400 dark:text-white/40 border border-transparent group-hover:border-white/10 group-hover:bg-white/10"
                          }`}>
                            {milestone.date}
                          </span>
                        </div>
                        
                        <p className="text-sm text-slate-500 dark:text-white/70 font-light leading-relaxed group-hover:text-slate-700 dark:group-hover:text-white/95 transition-colors duration-300">
                          {milestone.description}
                        </p>

                        {isInProgress && (
                          <motion.div 
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.4 }}
                            className={`pt-4 flex ${isEven ? 'md:justify-start' : 'md:justify-end'}`}
                          >
                            <motion.button 
                              onClick={() => {
                                setSelectedMilestone(milestone);
                                setVerifyError("");
                              }}
                              whileHover={{ scale: 1.05, backgroundColor: "rgba(59,130,246,0.2)" }}
                              whileTap={{ scale: 0.95 }}
                              className="flex items-center gap-2 text-xs font-bold text-blue-500 dark:text-blue-400 transition-colors group/btn px-5 py-2.5 rounded-lg bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/30 shadow-[0_0_20px_rgba(59,130,246,0.2)] hover:shadow-[0_0_30px_rgba(59,130,246,0.4)] hover:text-blue-700 dark:hover:text-blue-200"
                            >
                              <Star className="w-4 h-4" />
                              <span>Start Target Tasks</span>
                              <ArrowRight className="w-4 h-4 transform group-hover/btn:translate-x-1.5 transition-transform" />
                            </motion.button>
                          </motion.div>
                        )}
                      </div>
                    </motion.div>
                  </motion.div>

                  {/* Stepper Center Icon */}
                  <div className="absolute left-8 md:left-1/2 -translate-x-1/2 flex items-center justify-center z-20">
                    <motion.div 
                      initial={{ scale: 0, rotate: -45 }}
                      whileInView={{ scale: 1, rotate: 0 }}
                      whileHover={{ scale: 1.25, rotate: isCompleted ? 360 : 15 }}
                      viewport={{ once: true, margin: "-100px" }}
                      transition={{ type: "spring", delay: 0.2 }}
                      className={`w-12 h-12 rounded-full flex items-center justify-center font-black text-sm backdrop-blur-xl transition-all duration-300 cursor-pointer ${
                        isCompleted 
                          ? "bg-emerald-100 dark:bg-emerald-900/40 text-emerald-600 dark:text-emerald-400 border-2 border-emerald-400 dark:border-emerald-500/40 shadow-[0_0_20px_rgba(16,185,129,0.3)] group-hover:shadow-[0_0_35px_rgba(16,185,129,0.6)] group-hover:bg-emerald-200 dark:group-hover:bg-emerald-800/60" 
                          : isInProgress 
                          ? "bg-blue-600 text-white border-2 border-blue-400/50 shadow-[0_0_25px_rgba(59,130,246,0.6)] group-hover:shadow-[0_0_40px_rgba(59,130,246,0.8)]" 
                          : "bg-slate-100 dark:bg-slate-900 text-slate-500 dark:text-slate-400 border-2 border-slate-300 dark:border-slate-700 group-hover:border-violet-500/40 group-hover:text-slate-900 dark:group-hover:text-white group-hover:shadow-[0_0_20px_rgba(139,92,246,0.3)]"
                      }`}
                    >
                      {isCompleted ? <CheckCircle2 className="w-6 h-6" /> : milestone.step}
                    </motion.div>
                  </div>

                  {/* Empty div for the other side to keep alternating layout balanced on desktop */}
                  <div className="hidden md:block w-[45%]" />
                </div>
              );
            })}
          </div>
        </div>
      )}

      {!isLoading && !error && milestones.length > 0 && milestones.every((m: Milestone) => m.status === "completed") && (
        <motion.div 
          initial={{ opacity: 0, scale: 0.9, y: 30 }}
          whileInView={{ opacity: 1, scale: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.7, type: "spring", bounce: 0.4 }}
          className="max-w-2xl mx-auto mt-8 relative"
        >
          <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/10 via-cyan-500/10 to-violet-500/10 blur-3xl -z-10" />
          <div className="glass-card p-10 flex flex-col items-center text-center border border-emerald-500/20 shadow-[0_0_50px_rgba(16,185,129,0.15)] relative overflow-hidden group">
            <div className="absolute inset-0 bg-emerald-500/5 group-hover:bg-emerald-500/10 transition-colors duration-500" />
            
            <div className="w-20 h-20 bg-gradient-to-br from-emerald-400 to-cyan-500 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(16,185,129,0.4)] relative z-10 group-hover:scale-110 transition-transform duration-500">
              <Star className="w-10 h-10 text-white fill-white" />
            </div>
            
            <h2 className="text-3xl md:text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 font-display mb-4 relative z-10">
              Ultimate Goal Achieved!
            </h2>
            
            <p className="text-slate-400 dark:text-white/70 text-lg max-w-lg mx-auto relative z-10 font-medium">
              Congratulations! By following this personalized roadmap, you will have mastered all missing skills and successfully secured your dream job placement. 
            </p>
          </div>
        </motion.div>
      )}
      {/* Modal for GitHub Verification */}
      <AnimatePresence>
        {selectedMilestone && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white dark:bg-[#0f172a] border border-slate-200 dark:border-white/10 p-8 rounded-2xl w-full max-w-lg shadow-[0_0_50px_rgba(0,0,0,0.5)] relative overflow-hidden"
            >
              <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[300px] rounded-full opacity-[0.1] pointer-events-none"
                style={{ background: "radial-gradient(circle, var(--accent-blue) 0%, transparent 70%)", filter: "blur(50px)" }} />

              <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-2 relative z-10">{selectedMilestone.title}</h3>
              <p className="text-sm text-slate-500 dark:text-slate-400 mb-6 relative z-10">Complete the learning resources and verify your skills to unlock the next milestone.</p>
              
              <div className="space-y-6 relative z-10">
                <div className="p-4 bg-slate-50 dark:bg-slate-900/50 rounded-xl border border-slate-200 dark:border-white/5">
                  <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3 flex items-center gap-2">
                    <Star className="w-4 h-4 text-amber-500 dark:text-amber-400" />
                    Recommended Resources
                  </h4>
                  <div className="space-y-4">
                    {(() => {
                      const targetSkills = (selectedMilestone as any).targetSkills || (selectedMilestone.targetSkill ? [selectedMilestone.targetSkill] : [selectedMilestone.title]);
                      const displayedSkills = expandedResources ? targetSkills : targetSkills.slice(0, 1);
                      
                      return (
                        <>
                          {displayedSkills.map((skill: string, idx: number) => (
                            <div key={idx}>
                              <div className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">{skill}</div>
                              <ul className="space-y-1.5 text-sm text-blue-500 dark:text-blue-400">
                                <li><a href={`https://www.freecodecamp.org/news/search/?query=${encodeURIComponent(skill)}`} target="_blank" rel="noreferrer" className="hover:underline">→ FreeCodeCamp Guide</a></li>
                                <li><a href={`https://github.com/search?q=${encodeURIComponent(skill + " tutorial")}&type=repositories`} target="_blank" rel="noreferrer" className="hover:underline">→ GitHub Repositories</a></li>
                                <li><a href={`https://www.youtube.com/results?search_query=${encodeURIComponent(skill + " full course tutorial")}`} target="_blank" rel="noreferrer" className="hover:underline">→ YouTube Crash Course</a></li>
                                <li><a href={`https://www.udemy.com/courses/search/?q=${encodeURIComponent(skill)}`} target="_blank" rel="noreferrer" className="hover:underline">→ Udemy Courses</a></li>
                                <li><a href={`https://www.coursera.org/search?query=${encodeURIComponent(skill)}`} target="_blank" rel="noreferrer" className="hover:underline">→ Coursera Courses</a></li>
                              </ul>
                            </div>
                          ))}
                          {!expandedResources && targetSkills.length > 1 && (
                            <button 
                              onClick={() => setExpandedResources(true)}
                              className="text-xs font-semibold text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 hover:underline w-full text-center pt-2"
                            >
                              + View {targetSkills.length - 1} More Topics
                            </button>
                          )}
                          {expandedResources && targetSkills.length > 1 && (
                            <button 
                              onClick={() => setExpandedResources(false)}
                              className="text-xs font-semibold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 hover:underline w-full text-center pt-2"
                            >
                              - Show Less
                            </button>
                          )}
                        </>
                      );
                    })()}
                  </div>
                </div>

                <div className="p-4 bg-blue-50 dark:bg-blue-950/20 rounded-xl border border-blue-200 dark:border-blue-500/20">
                  <h4 className="text-sm font-semibold text-blue-700 dark:text-blue-300 mb-2 flex items-center gap-2">
                    <Code className="w-4 h-4" />
                    GitHub Project Verification
                  </h4>
                  <p className="text-xs text-slate-600 dark:text-slate-400 mb-4">
                    Connect your GitHub account. We'll instantly scan your public repositories for matching languages and frameworks to prove your skills.
                  </p>
                  
                  {verifyError && (
                    <div className="mb-3 text-xs text-rose-400 bg-rose-500/10 p-2 rounded">
                      {verifyError}
                    </div>
                  )}

                  {needsGithubLink ? (
                    <button 
                      onClick={async () => {
                        try {
                          const { authClient } = await import('@/features/authentication/services/auth-service');
                          await authClient.signIn.social({
                            provider: "github",
                            callbackURL: window.location.href,
                          });
                        } catch (err) {
                          console.error("Failed to link GitHub", err);
                        }
                      }}
                      className="w-full bg-[#24292e] hover:bg-[#1b1f23] text-white px-4 py-3 rounded-lg text-sm font-semibold transition-colors flex items-center justify-center gap-2"
                    >
                      <svg height="20" viewBox="0 0 16 16" version="1.1" width="20" aria-hidden="true" fill="currentColor">
                        <path fillRule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
                      </svg>
                      Link GitHub Account
                    </button>
                  ) : (
                    <div className="flex gap-2">
                      <button 
                        onClick={async () => {
                          setIsVerifying(true);
                          setVerifyError("");
                          try {
                            const res = await api.post("/api/roadmap/verify-step", { step: selectedMilestone.step });
                            if (res.data.success) {
                              await queryClient.invalidateQueries({ queryKey: ["roadmap"] });
                              setSelectedMilestone(null);
                            } else {
                              setVerifyError(res.data.error || "Verification failed");
                            }
                          } catch (err: any) {
                            const errMsg = err.response?.data?.error || "Error verifying account.";
                            if (err.response?.status === 403 && errMsg.includes("link your GitHub account")) {
                              setNeedsGithubLink(true);
                            }
                            setVerifyError(errMsg);
                          } finally {
                            setIsVerifying(false);
                          }
                        }}
                        disabled={isVerifying}
                        className="w-full bg-blue-600 hover:bg-blue-500 text-white px-4 py-3 rounded-lg text-sm font-semibold transition-colors disabled:opacity-50 flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(37,99,235,0.2)]"
                      >
                        {isVerifying ? <Loader2 className="w-4 h-4 animate-spin" /> : "Verify Linked GitHub Account"}
                      </button>
                    </div>
                  )}
                </div>
              </div>

              <button 
                onClick={() => {
                  setSelectedMilestone(null);
                  setVerifyError("");
                  setNeedsGithubLink(false);
                  setExpandedResources(false);
                }} 
                className="absolute top-4 right-4 text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
